apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: masonnia/video-streaming:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
          readinessProbe:
            httpGet:
              path: /video
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
